#line 2 "tokens.cc"

#line 4 "tokens.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 1
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yynoreturn yy_fatal_error (yyconst char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 74
#define YY_END_OF_BUFFER 75
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[500] =
    {   0,
        0,    0,   75,   73,   71,   72,   67,   73,   66,   73,
       73,   73,   73,   73,   63,   63,   63,   63,   62,   63,
       63,   63,   63,   63,   63,   61,   63,   71,   66,    0,
       66,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   70,
       68,   69,   65,   65,   63,   63,   63,   53,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       49,   63,   63,   63,   63,   63,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,   65,   65,   57,   48,   63,   63,
       63,   56,   63,   63,   63,   63,   63,   47,   63,   63,
       63,   63,   63,   63,   63,    0,   19,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   65,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   54,   63,   63,   63,
       46,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   41,   40,    0,    0,   25,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,   65,   63,   63,   63,   63,   63,
       50,   63,   63,   63,   63,   63,   55,   63,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   30,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   29,    0,    0,    5,    0,    0,   65,    1,
        2,   45,   51,   52,   63,   63,   43,   44,   63,   63,
       26,    0,    0,    0,    0,    0,    0,   38,    0,   36,
        0,    0,    0,    0,   42,    0,    0,    0,    0,    0,
        0,    0,    0,    9,    0,   10,    0,   65,   63,   63,
        3,   63,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,   18,    0,    0,   39,    0,    0,    0,    0,
        0,    0,    0,    0,   65,   59,   58,   63,    0,    0,
        0,    0,    0,    0,   33,    0,   13,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   64,   63,
       37,   35,    6,    0,    0,    0,    0,    0,    0,    8,
        0,   31,    0,    0,    0,    0,    0,    0,    0,   60,
        0,    0,    0,    0,    0,    0,    0,    0,   32,    0,
        7,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   34,    0,    4,    0,

        0,    0,    0,   28,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   24,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   27,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   20,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   22,    0,    0,    0,    0,    0,    0,
        0,   17,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   21,    0,    0,
        0,    0,    0,    0,    0,   11,    0,   23,    0,    0,
        0,    0,   15,    0,    0,   16,   12,   14,    0

    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    4,
        4,    4,    4,    1,    5,    6,    4,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    8,    9,   10,
       11,   12,   13,    1,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
        1,    1,    1,    1,   40,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
       55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
       65,   66,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[67] =
    {   0,
        1,    1,    1,    1,    2,    1,    2,    1,    1,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    2,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3
    } ;

static yyconst flex_uint16_t yy_base[504] =
    {   0,
        0,    0,  987,  997,  984,  997,  997,  978,   61,   55,
      980,  971,  970,   53,   92,    0,   75,   96,   50,   53,
      107,   94,  112,   93,   93,  103,  111,  977,  969,  968,
       84,  118,  108,  147,  147,  139,  112,  114,  149,  154,
      162,  163,  175,  148,  165,  152,  175,  160,  971,  997,
      997,  997,    0,  154,    0,  165,  178,    0,  182,  192,
      186,  203,  201,  194,  197,  190,  202,  197,  205,  209,
        0,  216,  207,  222,  204,  220,  206,  216,  216,  228,
      216,  223,  220,  236,  226,  245,  238,  246,  260,  255,
      252,  247,  255,  263,  261,  268,  255,  270,  275,  260,

      274,  265,  264,  273,    0,  265,    0,    0,  275,  284,
      281,    0,  271,  295,  289,  299,  304,    0,  312,  310,
      300,  318,  303,  321,  310,  316,  997,  310,  335,  314,
      320,  330,  331,  328,  333,  317,  332,  335,  331,  324,
      335,  332,  357,  366,  363,  364,  371,  371,  362,  357,
      363,  371,  378,  379,  363,  385,  373,  381,  386,  372,
      381,  372,  385,  387,  399,  405,    0,  397,  396,  409,
        0,  407,  408,  417,  408,  420,  417,  411,  424,  414,
      434,  426,  419,  426,  421,  997,  997,  423,  435,  997,
      425,  443,  429,  438,  437,  445,  438,  453,  444,  454,

      471,  457,  463,  475,  462,  478,  470,  468,  468,  476,
        0,  482,  483,  475,  474,  490,    0,  964,  482,  479,
      479,  499,  487,  489,  492,  494,  503,  496,  508,  519,
      509,  521,  997,  528,  525,  516,  528,  533,  526,  538,
      533,  527,  997,  527,  335,  997,  540,  530,  540,    0,
        0,    0,    0,    0,  524,  526,    0,    0,  540,  534,
      997,  546,  550,  546,  541,  551,  567,  997,  556,  997,
      563,  570,  566,  573,  997,  568,  572,  578,  574,  591,
      595,  593,  595,  997,  592,  997,  583,  588,  599,  601,
        0,  598,  588,  594,  593,  599,  597,  600,  610,  620,

      607,  617,  997,  624,  634,  997,  635,  639,  636,  626,
      639,  636,  636,  652,  640,    0,    0,  642,  651,  643,
      639,  639,  652,  653,  181,  174,  997,  654,  648,  152,
      649,  652,  654,  673,  674,  681,  682,  680,    0,  688,
      997,  695,  997,  679,  679,  678,  693,  702,  703,  997,
      691,  997,  689,  700,  691,  707,  698,  694,  137,    0,
      703,  134,  707,  712,  707,  719,  712,  710,  997,  717,
      997,  133,  713,  731,  729,  132,  741,  732,   90,  745,
      732,   89,  748,  740,  740,  738,  757,  743,  757,  757,
      750,  749,  749,  759,  753,  767,  997,  753,  997,  763,

      771,  772,  776,  767,  769,  773,  784,  782,  786,  799,
       87,  803,  801,  803,  997,  805,  810,  798,  810,  802,
      814,  806,  804,  815,  819,  820,  812,  806,  826,  826,
      817,  827,  826,  838,  828,  838,  845,  997,  840,  849,
      846,  841,  858,  844,  846,  852,  849,  856,  851,  868,
      868,  865,  857,  997,  873,  869,  875,  874,  875,  868,
      870,  997,  885,  890,  893,  892,  888,  908,  903,  894,
      896,  896,  904,  910,  908,  908,  915,  997,  916,  907,
      912,  909,  916,  916,  917,  997,  919,  997,  918,  924,
      926,  925,  997,  929,  930,  997,  997,  997,  997,  989,

       73,  991,  993
    } ;

static yyconst flex_int16_t yy_def[504] =
    {   0,
      499,    1,  499,  499,  499,  499,  499,  499,  499,  499,
      500,  499,  499,  501,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  500,  499,
      499,  499,  503,  503,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,

      499,  499,  499,  499,  503,  503,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  503,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      502,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,

      499,  499,  499,  499,  503,  502,  502,  502,  502,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  503,  502,
      502,  502,  502,  502,  502,  502,  502,  502,  502,  502,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  503,  502,  502,
      502,  502,  499,  499,  499,  499,  499,  499,  499,  499,

      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  503,  502,  502,  502,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  503,  502,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  502,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,

      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,    0,  499,

      499,  499,  499
    } ;

static yyconst flex_uint16_t yy_nxt[1064] =
    {   0,
        4,    5,    6,    7,    7,    8,    9,   10,   11,   12,
        7,   13,   14,   15,   16,   16,   17,   18,   19,   16,
       16,   20,   16,   16,   16,   21,   22,   23,   24,   16,
       16,   25,   26,   16,   16,   27,   16,   16,   16,    4,
       15,   16,   16,   17,   18,   19,   16,   16,   20,   16,
       16,   16,   21,   22,   23,   24,   16,   16,   25,   26,
       16,   16,   27,   16,   16,   16,   30,   31,   32,   54,
       33,   34,   35,   36,   37,   53,   38,   64,   65,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   30,
       31,  422,   59,  395,  392,   32,   54,   33,   34,   35,

       36,   37,   60,   38,   64,   65,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   56,   61,   57,   59,
       66,   68,   62,   73,   58,   74,   70,   69,   67,   60,
       75,   76,   63,   77,   78,   79,  389,  385,  377,   89,
       90,  375,   71,   56,   61,   57,   72,   66,   68,   62,
       73,   58,   74,   70,   69,   67,  351,   75,   76,   63,
       77,   78,   79,   87,   80,   84,   89,   90,   81,   71,
       91,   92,   88,   72,   82,   93,   85,   95,  348,   94,
       83,   99,  100,   86,  101,  347,  104,  106,   97,  107,
       87,   80,   84,   96,  108,   81,  102,   91,   92,   88,

      109,   82,   93,   85,   95,   98,   94,   83,   99,  100,
       86,  101,  103,  104,  106,   97,  107,  110,  111,  112,
       96,  108,  113,  102,  114,  115,  116,  109,  117,  118,
      119,  120,   98,  121,  122,  123,  124,  125,  126,  103,
      127,  128,  129,  130,  110,  111,  112,  131,  132,  113,
      133,  114,  115,  116,  134,  117,  118,  119,  120,  135,
      121,  122,  123,  124,  125,  126,  136,  127,  128,  129,
      130,  137,  138,  139,  131,  132,  140,  133,  141,  142,
      143,  134,  144,  145,  146,  147,  135,  148,  149,  150,
      153,  151,  154,  136,  155,  156,  157,  158,  137,  138,

      139,  159,  160,  140,  152,  141,  142,  143,  161,  144,
      145,  146,  147,  162,  148,  149,  150,  153,  151,  154,
      163,  155,  156,  157,  158,  164,  165,  166,  159,  160,
      167,  152,  168,  169,  170,  161,  171,  172,  173,  285,
      162,  177,  178,  179,  180,  181,  182,  163,  183,  184,
      185,  174,  164,  165,  166,  186,  187,  167,  188,  168,
      169,  170,  189,  171,  172,  173,  175,  176,  177,  178,
      179,  180,  181,  182,  190,  183,  184,  185,  174,  191,
      192,  193,  186,  187,  194,  188,  195,  196,  197,  189,
      198,  199,  200,  175,  176,  201,  202,  204,  205,  206,

      203,  190,  207,  208,  209,  210,  191,  192,  193,  211,
      212,  194,  213,  195,  196,  197,  214,  198,  199,  200,
      215,  216,  201,  202,  204,  205,  206,  203,  217,  207,
      208,  209,  210,  218,  219,  220,  211,  212,  221,  213,
      222,  223,  224,  214,  225,  226,  227,  215,  216,  228,
      229,  230,  231,  232,  233,  217,  234,  235,  236,  237,
      218,  219,  220,  238,  239,  221,  240,  222,  223,  224,
      241,  225,  226,  227,  242,  243,  228,  229,  230,  231,
      232,  233,  244,  234,  235,  236,  237,  245,  246,  247,
      238,  239,  248,  240,  249,  250,  251,  241,  252,  253,

      254,  242,  243,  255,  256,  257,  258,  259,  261,  244,
      262,  263,  264,  265,  245,  246,  247,  266,  267,  248,
      268,  249,  250,  251,  269,  252,  253,  254,  270,  271,
      255,  256,  257,  258,  259,  261,  272,  262,  263,  264,
      265,  273,  274,  275,  266,  267,  276,  268,  277,  278,
      279,  269,  280,  281,  282,  270,  271,  283,  284,  286,
      287,  288,  289,  272,  290,  291,  292,  293,  273,  274,
      275,  294,  295,  276,  296,  277,  278,  279,  297,  280,
      281,  282,  298,  299,  283,  284,  286,  287,  288,  289,
      300,  290,  291,  292,  293,  301,  302,  303,  294,  295,

      304,  296,  305,  306,  307,  297,  308,  309,  310,  298,
      299,  311,  312,  313,  314,  315,  316,  300,  317,  318,
      319,  320,  301,  302,  303,  321,  322,  304,  323,  305,
      306,  307,  324,  308,  309,  310,  325,  326,  311,  312,
      313,  314,  315,  316,  327,  317,  318,  319,  320,  328,
      329,  330,  321,  322,  331,  323,  332,  333,  334,  324,
      335,  336,  337,  325,  326,  338,  339,  340,  341,  342,
      343,  327,  344,  345,  346,  349,  328,  329,  330,  350,
      352,  331,  353,  332,  333,  334,  354,  335,  336,  337,
      355,  356,  338,  339,  340,  341,  342,  343,  357,  344,

      345,  346,  349,  358,  359,  360,  350,  352,  361,  353,
      362,  363,  364,  354,  365,  366,  367,  355,  356,  368,
      369,  370,  371,  372,  373,  357,  374,  376,  378,  379,
      358,  359,  360,  380,  381,  361,  382,  362,  363,  364,
      383,  365,  366,  367,  384,  386,  368,  369,  370,  371,
      372,  373,  387,  374,  376,  378,  379,  388,  390,  391,
      380,  381,  393,  382,  394,  396,  397,  383,  398,  399,
      400,  384,  386,  401,  402,  403,  404,  405,  406,  387,
      407,  408,  409,  410,  388,  390,  391,  411,  412,  393,
      413,  394,  396,  397,  414,  398,  399,  400,  415,  416,

      401,  402,  403,  404,  405,  406,  417,  407,  408,  409,
      410,  418,  419,  420,  411,  412,  421,  413,  423,  424,
      425,  414,  426,  427,  428,  415,  416,  429,  430,  431,
      432,  433,  434,  417,  435,  436,  437,  438,  418,  419,
      420,  439,  440,  421,  441,  423,  424,  425,  442,  426,
      427,  428,  443,  444,  429,  430,  431,  432,  433,  434,
      445,  435,  436,  437,  438,  446,  447,  448,  439,  440,
      449,  441,  450,  451,  452,  442,  453,  454,  455,  443,
      444,  456,  457,  458,  459,  460,  461,  445,  462,  463,
      464,  465,  446,  447,  448,  466,  467,  449,  468,  450,

      451,  452,  469,  453,  454,  455,  470,  471,  456,  457,
      458,  459,  460,  461,  472,  462,  463,  464,  465,  473,
      474,  475,  466,  467,  476,  468,  477,  478,  479,  469,
      480,  481,  482,  470,  471,  483,  484,  485,  486,  487,
      488,  472,  489,  490,  491,  492,  473,  474,  475,  493,
      494,  476,  495,  477,  478,  479,  496,  480,  481,  482,
      497,  498,  483,  484,  485,  486,  487,  488,  260,  489,
      490,  491,  492,   50,   29,   29,  493,  494,   28,  495,
       52,   51,   50,  496,   29,   28,  499,  497,  498,   49,
       49,   49,   55,   55,  105,  105,    3,  499,  499,  499,

      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499
    } ;

static yyconst flex_int16_t yy_chk[1064] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    9,    9,   10,   14,
       10,   10,   10,   10,   10,  501,   10,   19,   20,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   31,
       31,  411,   17,  382,  379,   10,   14,   10,   10,   10,

       10,   10,   17,   10,   19,   20,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   15,   18,   15,   17,
       21,   22,   18,   24,   15,   25,   23,   22,   21,   17,
       26,   27,   18,   32,   32,   33,  376,  372,  362,   37,
       38,  359,   23,   15,   18,   15,   23,   21,   22,   18,
       24,   15,   25,   23,   22,   21,  330,   26,   27,   18,
       32,   32,   33,   36,   34,   35,   37,   38,   34,   23,
       39,   40,   36,   23,   34,   41,   35,   42,  326,   41,
       34,   44,   45,   35,   46,  325,   48,   54,   43,   56,
       36,   34,   35,   42,   57,   34,   47,   39,   40,   36,

       59,   34,   41,   35,   42,   43,   41,   34,   44,   45,
       35,   46,   47,   48,   54,   43,   56,   60,   61,   62,
       42,   57,   63,   47,   64,   65,   66,   59,   67,   68,
       69,   70,   43,   72,   73,   74,   75,   76,   77,   47,
       78,   79,   79,   80,   60,   61,   62,   81,   82,   63,
       83,   64,   65,   66,   84,   67,   68,   69,   70,   85,
       72,   73,   74,   75,   76,   77,   86,   78,   79,   79,
       80,   87,   88,   89,   81,   82,   90,   83,   91,   92,
       93,   84,   94,   95,   96,   97,   85,   98,   99,  100,
      102,  101,  103,   86,  104,  106,  109,  110,   87,   88,

       89,  111,  113,   90,  101,   91,   92,   93,  114,   94,
       95,   96,   97,  115,   98,   99,  100,  102,  101,  103,
      116,  104,  106,  109,  110,  117,  119,  120,  111,  113,
      121,  101,  122,  123,  124,  114,  125,  126,  128,  245,
      115,  130,  131,  132,  133,  134,  135,  116,  136,  137,
      138,  129,  117,  119,  120,  139,  140,  121,  141,  122,
      123,  124,  142,  125,  126,  128,  129,  129,  130,  131,
      132,  133,  134,  135,  143,  136,  137,  138,  129,  144,
      145,  146,  139,  140,  147,  141,  148,  148,  149,  142,
      150,  151,  152,  129,  129,  153,  154,  155,  156,  157,

      154,  143,  158,  159,  160,  161,  144,  145,  146,  162,
      163,  147,  164,  148,  148,  149,  165,  150,  151,  152,
      166,  168,  153,  154,  155,  156,  157,  154,  169,  158,
      159,  160,  161,  170,  172,  173,  162,  163,  174,  164,
      175,  176,  177,  165,  178,  179,  180,  166,  168,  181,
      182,  183,  184,  185,  188,  169,  189,  191,  192,  193,
      170,  172,  173,  194,  195,  174,  196,  175,  176,  177,
      197,  178,  179,  180,  198,  199,  181,  182,  183,  184,
      185,  188,  200,  189,  191,  192,  193,  201,  202,  203,
      194,  195,  204,  196,  205,  206,  207,  197,  208,  209,

      210,  198,  199,  212,  213,  214,  215,  216,  219,  200,
      220,  221,  222,  223,  201,  202,  203,  224,  225,  204,
      226,  205,  206,  207,  227,  208,  209,  210,  228,  229,
      212,  213,  214,  215,  216,  219,  230,  220,  221,  222,
      223,  231,  232,  234,  224,  225,  235,  226,  236,  237,
      238,  227,  239,  240,  241,  228,  229,  242,  244,  247,
      248,  249,  255,  230,  256,  259,  260,  262,  231,  232,
      234,  263,  264,  235,  265,  236,  237,  238,  266,  239,
      240,  241,  267,  269,  242,  244,  247,  248,  249,  255,
      269,  256,  259,  260,  262,  271,  272,  273,  263,  264,

      274,  265,  276,  277,  278,  266,  279,  280,  281,  267,
      269,  282,  283,  285,  287,  288,  289,  269,  290,  292,
      293,  294,  271,  272,  273,  295,  296,  274,  297,  276,
      277,  278,  298,  279,  280,  281,  299,  300,  282,  283,
      285,  287,  288,  289,  301,  290,  292,  293,  294,  302,
      304,  305,  295,  296,  307,  297,  308,  309,  310,  298,
      311,  312,  313,  299,  300,  314,  315,  318,  319,  320,
      321,  301,  322,  323,  324,  328,  302,  304,  305,  329,
      331,  307,  332,  308,  309,  310,  333,  311,  312,  313,
      334,  335,  314,  315,  318,  319,  320,  321,  336,  322,

      323,  324,  328,  337,  338,  340,  329,  331,  342,  332,
      344,  345,  346,  333,  347,  348,  349,  334,  335,  351,
      353,  354,  355,  356,  357,  336,  358,  361,  363,  364,
      337,  338,  340,  365,  366,  342,  367,  344,  345,  346,
      368,  347,  348,  349,  370,  373,  351,  353,  354,  355,
      356,  357,  374,  358,  361,  363,  364,  375,  377,  378,
      365,  366,  380,  367,  381,  383,  384,  368,  385,  386,
      387,  370,  373,  388,  389,  390,  391,  392,  393,  374,
      394,  395,  396,  398,  375,  377,  378,  400,  401,  380,
      402,  381,  383,  384,  403,  385,  386,  387,  404,  405,

      388,  389,  390,  391,  392,  393,  406,  394,  395,  396,
      398,  407,  408,  409,  400,  401,  410,  402,  412,  413,
      414,  403,  416,  417,  418,  404,  405,  419,  420,  421,
      422,  423,  424,  406,  425,  426,  427,  428,  407,  408,
      409,  429,  430,  410,  431,  412,  413,  414,  432,  416,
      417,  418,  433,  434,  419,  420,  421,  422,  423,  424,
      435,  425,  426,  427,  428,  436,  437,  439,  429,  430,
      440,  431,  441,  442,  443,  432,  444,  445,  446,  433,
      434,  447,  448,  449,  450,  451,  452,  435,  453,  455,
      456,  457,  436,  437,  439,  458,  459,  440,  460,  441,

      442,  443,  461,  444,  445,  446,  463,  464,  447,  448,
      449,  450,  451,  452,  465,  453,  455,  456,  457,  466,
      467,  468,  458,  459,  469,  460,  470,  471,  472,  461,
      473,  474,  475,  463,  464,  476,  477,  479,  480,  481,
      482,  465,  483,  484,  485,  487,  466,  467,  468,  489,
      490,  469,  491,  470,  471,  472,  492,  473,  474,  475,
      494,  495,  476,  477,  479,  480,  481,  482,  218,  483,
      484,  485,  487,   49,   30,   29,  489,  490,   28,  491,
       13,   12,   11,  492,    8,    5,    3,  494,  495,  500,
      500,  500,  502,  502,  503,  503,  499,  499,  499,  499,

      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "tokens.ll"
/* -*-C++-*- */
/*
 * PDDL tokenizer.
 *
 * Copyright (C) 2002-2004 Carnegie Mellon University
 * Written by Håkan L. S. Younes.
 *
 * Permission is hereby granted to distribute this software for
 * non-commercial research purposes, provided that this copyright
 * notice is included with any such distribution.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
 * EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE.  THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE
 * SOFTWARE IS WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU
 * ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.
 *
 * $Id: tokens.ll,v 6.4 2003-09-18 21:52:29 lorens Exp $
 */
#line 22 "tokens.ll"
struct Condition;
struct Formula;
struct Literal;
struct Atom;
struct Expression;
struct Fluent;
struct Term;
struct Type;
struct TypeSet;
struct Step;
struct Ordering;
struct Link;

#include <cctype>
#include <string>
#include <vector>
#include "pddl.hh"


/* Current line number. */
size_t line_number;

/* Allocates a string containing the lowercase characters of the given
   C string, and returns the given token. */
static int make_string(const char* s, int token);

/* Makes a number of the given string, and return the NUMBER token. */
static int make_number(const char* s);

#line 906 "tokens.cc"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

			int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 57 "tokens.ll"


#line 1125 "tokens.cc"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 500 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 499 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 59 "tokens.ll"
return make_string(yytext, DEFINE);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 60 "tokens.ll"
return make_string(yytext, DOMAIN_TOKEN);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 61 "tokens.ll"
return make_string(yytext, PROBLEM);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 62 "tokens.ll"
return REQUIREMENTS;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 63 "tokens.ll"
return TYPES;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 64 "tokens.ll"
return CONSTANTS;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 65 "tokens.ll"
return PREDICATES;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 66 "tokens.ll"
return FUNCTIONS;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 67 "tokens.ll"
return STRIPS;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 68 "tokens.ll"
return TYPING;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 69 "tokens.ll"
return NEGATIVE_PRECONDITIONS;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 70 "tokens.ll"
return DISJUNCTIVE_PRECONDITIONS;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 71 "tokens.ll"
return EQUALITY;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 72 "tokens.ll"
return EXISTENTIAL_PRECONDITIONS;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 73 "tokens.ll"
return UNIVERSAL_PRECONDITIONS;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 74 "tokens.ll"
return QUANTIFIED_PRECONDITIONS;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 75 "tokens.ll"
return CONDITIONAL_EFFECTS;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 76 "tokens.ll"
return FLUENTS;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 77 "tokens.ll"
return ADL;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 78 "tokens.ll"
return DURATIVE_ACTIONS;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 79 "tokens.ll"
return DURATION_INEQUALITIES;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 80 "tokens.ll"
return CONTINUOUS_EFFECTS;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 81 "tokens.ll"
return TIMED_INITIAL_LITERALS;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 82 "tokens.ll"
return DECOMPOSITIONS;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 83 "tokens.ll"
return DECOMPOSITION_NAME;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 84 "tokens.ll"
return ACTION;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 85 "tokens.ll"
return DURATIVE_ACTION;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 86 "tokens.ll"
return DECOMPOSITION;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 87 "tokens.ll"
return STEPS;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 88 "tokens.ll"
return LINKS;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 89 "tokens.ll"
return ORDERINGS;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 90 "tokens.ll"
return PARAMETERS;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 91 "tokens.ll"
return DURATION;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 92 "tokens.ll"
return PRECONDITION;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 93 "tokens.ll"
return CONDITION;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 94 "tokens.ll"
return EFFECT;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 95 "tokens.ll"
return COMPOSITE;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 96 "tokens.ll"
return PDOMAIN;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 97 "tokens.ll"
return OBJECTS;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 98 "tokens.ll"
return INIT;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 99 "tokens.ll"
return GOAL;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 100 "tokens.ll"
return METRIC;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 101 "tokens.ll"
return make_string(yytext, NUMBER_TOKEN);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 102 "tokens.ll"
return make_string(yytext, OBJECT_TOKEN);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 103 "tokens.ll"
return make_string(yytext, EITHER);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 104 "tokens.ll"
return make_string(yytext, WHEN);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 105 "tokens.ll"
return make_string(yytext, NOT);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 106 "tokens.ll"
return make_string(yytext, AND);
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 107 "tokens.ll"
return make_string(yytext, OR);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 108 "tokens.ll"
return make_string(yytext, IMPLY);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 109 "tokens.ll"
return make_string(yytext, EXISTS);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 110 "tokens.ll"
return make_string(yytext, FORALL);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 111 "tokens.ll"
return make_string(yytext, AT);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 112 "tokens.ll"
return make_string(yytext, OVER);
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 113 "tokens.ll"
return make_string(yytext, START);
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 114 "tokens.ll"
return make_string(yytext, END);
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 115 "tokens.ll"
return make_string(yytext, ALL);
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 116 "tokens.ll"
return make_string(yytext, MINIMIZE);
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 117 "tokens.ll"
return make_string(yytext, MAXIMIZE);
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 118 "tokens.ll"
return make_string(yytext, TOTAL_TIME);
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 119 "tokens.ll"
return yytext[0];
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 120 "tokens.ll"
return yytext[0];
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 121 "tokens.ll"
return make_string(yytext, NAME);
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 122 "tokens.ll"
return make_string(yytext, DURATION_VAR);
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 123 "tokens.ll"
return make_string(yytext, VARIABLE);
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 124 "tokens.ll"
return make_number(yytext);
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 125 "tokens.ll"
return yytext[0];
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 126 "tokens.ll"
return LE;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 127 "tokens.ll"
return GE;
	YY_BREAK
case 70:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 128 "tokens.ll"
/* comment */
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 129 "tokens.ll"
/* whitespace */
	YY_BREAK
case 72:
/* rule 72 can match eol */
YY_RULE_SETUP
#line 130 "tokens.ll"
line_number++;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 131 "tokens.ll"
return ILLEGAL_TOKEN;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 133 "tokens.ll"
ECHO;
	YY_BREAK
#line 1552 "tokens.cc"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 500 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 500 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
	yy_is_jam = (yy_current_state == 499);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,(int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 133 "tokens.ll"



/* Allocates a string containing the lowercase characters of the given
   C string, and returns the given token. */
static int make_string(const char* s, int token) {
  std::string* result = new std::string();
  for (const char* p = s; *p != '\0'; p++) {
    *result += tolower(*p);
  }
  yylval.str = result;
  return token;
}


/* Makes a number of the given string, and return the NUMBER token. */
static int make_number(const char* s) {
  yylval.num = atof(s);
  return NUMBER;
}

